import { webLightTheme, type Theme } from '@fluentui/react-components'
import { fluentTokens } from './fluentTokens.js'

export const okpFluentTheme: Theme = {
  ...webLightTheme,
  fontFamilyBase: 'Inter, "Segoe UI", sans-serif',
  colorNeutralBackground1: fluentTokens.color.surface,
  colorNeutralBackground2: fluentTokens.color.surfaceSubtle,
  colorNeutralBackground3: fluentTokens.color.surface,
  colorNeutralForeground1: fluentTokens.color.text,
  colorNeutralForeground2: fluentTokens.color.textMuted,
  colorNeutralStroke1: fluentTokens.color.border,
  colorNeutralStrokeAccessible: fluentTokens.color.border,
  colorBrandBackground: fluentTokens.color.accent,
  colorBrandBackgroundHover: fluentTokens.color.accentHover,
  colorBrandForeground1: fluentTokens.color.accent,
  colorStatusDangerForeground1: fluentTokens.color.statusDanger,
  colorStatusSuccessForeground1: fluentTokens.color.statusSuccess,
  borderRadiusSmall: fluentTokens.radius.control,
  borderRadiusMedium: fluentTokens.radius.panel,
  borderRadiusLarge: fluentTokens.radius.overlay,
  shadow2: fluentTokens.elevation.shell,
  shadow4: fluentTokens.elevation.panel,
  shadow8: fluentTokens.elevation.overlay,
  shadow16: fluentTokens.elevation.dialog,
  spacingHorizontalXS: fluentTokens.spacing.xs,
  spacingHorizontalS: fluentTokens.spacing.sm,
  spacingHorizontalM: fluentTokens.spacing.md,
  spacingHorizontalL: fluentTokens.spacing.lg,
  spacingHorizontalXL: fluentTokens.spacing.xl,
  spacingVerticalXS: fluentTokens.spacing.xs,
  spacingVerticalS: fluentTokens.spacing.sm,
  spacingVerticalM: fluentTokens.spacing.md,
  spacingVerticalL: fluentTokens.spacing.lg,
  spacingVerticalXL: fluentTokens.spacing.xl,
}
